"""
Source Registry — начальный список источников.
Запусти: python -m src.database.seed_sources
"""

from src.database.db import get_conn, init_db

SOURCES = [
    # ── Агрегаторы высокой плотности ──────────────────────────────────────────
    {
        "source_id": "nyfa_opportunities",
        "name": "NYFA Opportunities — Visual Arts Grants",
        "url": "https://www.nyfa.org/opportunities/?discipline=Visual+Arts&type=Grant",
        "source_type": "aggregator",
        "region": "usa",
        "crawl_frequency": "weekly",
        "parser_type": "dynamic_js",
        "trust_level": 5,
        "notes": "Подтверждено: JS-рендеринг, Playwright. 48K символов контента.",
    },
    {
        "source_id": "artconnect",
        "parser_type": "listing",
        "name": "ArtConnect Grants & Stipends",
        "url": "https://www.artconnect.com/opportunities/grant-or-stipend",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "daily",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Международные гранты, стипендии, open calls. Актуальный URL с фильтром.",
    },
    {
        "source_id": "on_the_move",
        "name": "On the Move — Funding Guides",
        "url": "https://on-the-move.org/resources/funding",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "2000+ grants, scholarships, residencies. Mobility и international funding.",
    },
    {
        "source_id": "culture_moves_europe",
        "name": "Culture Moves Europe",
        "url": "https://culture.ec.europa.eu/culture-moves-europe",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Европейская mobility-схема для artists, включая visual arts.",
    },
    {
        "source_id": "transartists",
        "status": "inactive",
        "name": "TransArtists / DutchCulture Funding",
        "url": "https://www.transartists.org/en/opportunities",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Резиденции и funding for residencies, международная мобильность.",
    },
    {
        "source_id": "res_artis",
        "status": "inactive",
        "name": "Res Artis — Open Calls & Funding",
        "url": "https://www.resartis.org/en/opportunities/",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Residency-related funding и open calls от мировых резиденций.",
    },
    {
        "source_id": "artdeadline",
        "name": "ArtDeadline.com — Grants",
        "url": "https://artdeadline.com/?type=Grant",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "daily",
        "parser_type": "listing",
        "trust_level": 4,
        "notes": "Листинг-агрегатор. Парсим каждую страницу /ops/ отдельно через listing_fetcher.",
    },
    {
        "source_id": "submittable_discover",
        "name": "Submittable Discover — Grants",
        "url": "https://www.submittable.com/discover/?category=grants&q=visual+art",
        "source_type": "submission_platform",
        "region": "international",
        "crawl_frequency": "daily",
        "parser_type": "dynamic_js",
        "trust_level": 4,
        "notes": "Marketplace. JS-рендеринг через Playwright.",
    },
    {
        "source_id": "beam_arts",
        "name": "Beam Arts — Artist Funding Directory",
        "url": "https://www.beamarts.gr/artist-funding-directory",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Каталог grants/funding worldwide для artists. Обновлён февраль 2026.",
    },
    {
        "source_id": "fractured_atlas", "status": "inactive",
        "name": "Fractured Atlas — Artist Opportunity Database",
        "url": "https://fracturedatlas.notion.site/Artist-Opportunity-Database",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Notion-база: grants, funders, awards, fellowships, open calls, residencies worldwide.",
    },

    # ── Прямые фонды — визуальное искусство ────────────────────────────────────
    {
        "source_id": "fca_emergency",
        "name": "Foundation for Contemporary Arts — Emergency Grants",
        "url": "https://www.foundationforcontemporaryarts.org/grants/emergency-grants/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Срочные гранты $500-$3,000 для visual и performing artists в США. Открыты круглый год.",
    },
    {
        "source_id": "creative_capital",
        "name": "Creative Capital Foundation",
        "url": "https://creative-capital.org/awards/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "dynamic_js",
        "trust_level": 5,
        "notes": "JS-рендеринг, Playwright. Страница awards с актуальными грантами.",
    },
    {
        "source_id": "sustainable_arts",
        "name": "Sustainable Arts Foundation",
        "url": "https://www.sustainableartsfoundation.org/awards",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "$5,000 x 20 художников. Для artists с детьми.",
    },
    {
        "source_id": "artadia",
        "name": "Artadia Awards",
        "url": "https://artadia.org/awards/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "HTML + JSON-LD. Дедлайны по городам (LA, Chicago, NYC, SF).",
    },
    {
        "source_id": "macdowell",
        "name": "MacDowell Fellowships",
        "url": "https://macdowell.org/fellowships/",
        "source_type": "residency",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Residency fellowships, включая visual arts.",
    },
    {
        "source_id": "joan_mitchell",
        "name": "Joan Mitchell Foundation — Grants",
        "url": "https://www.joanmitchellfoundation.org/artist-programs/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Grants для visual artists.",
    },
    {
        "source_id": "pollock_krasner",
        "name": "Pollock-Krasner Foundation",
        "url": "https://pkf.org/our-grants/",
        "source_type": "fund",
        "region": "international",
        "crawl_frequency": "monthly",
        "parser_type": "dynamic_js",
        "trust_level": 5,
        "notes": "Playwright нужен.",
    },
    {
        "source_id": "usa_artists",
        "name": "United States Artists",
        "url": "https://www.unitedstatesartists.org/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "USA Fellows program.",
    },
    {
        "source_id": "anonymous_was_a_woman",
        "name": "Anonymous Was A Woman",
        "url": "https://anonymouswasawoman.org/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "$25,000 grants to women visual artists 45+.",
    },
    {
        "source_id": "andy_warhol_fnd",
        "name": "Andy Warhol Foundation for the Visual Arts",
        "url": "https://warholfoundation.org/grants/",
        "source_type": "fund",
        "region": "international",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Гранты организациям, поддерживающим contemporary visual art.",
    },
    {
        "source_id": "jerome_fnd",
        "name": "Jerome Foundation",
        "url": "https://www.jeromefdn.org/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "dynamic_js",
        "trust_level": 4,
        "notes": "Playwright нужен.",
    },

    # ── Европейские и международные фонды ─────────────────────────────────────
    {
        "source_id": "british_council_arts", "status": "inactive",
        "name": "British Council — Arts Funding",
        "url": "https://www.britishcouncil.org/arts/funding",
        "source_type": "government",
        "region": "uk",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Mobility и international arts grants от British Council.",
    },
    {
        "source_id": "goethe_fnd",
        "status": "inactive",
        "name": "Goethe-Institut — Grants & Residencies",
        "url": "https://www.goethe.de/en/kul/the/prg.html",
        "source_type": "government",
        "region": "international",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Стипендии, резиденции, проектные гранты.",
    },
    {
        "source_id": "pro_helvetia",
        "name": "Pro Helvetia — Swiss Arts Council",
        "url": "https://prohelvetia.ch/en/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Grants for international projects.",
    },

    # ── Новые источники — Европа ──────────────────────────────────────────────
    {
        "source_id": "stiftung_kunstfonds",
        "name": "Stiftung Kunstfonds",
        "url": "https://www.kunstfonds.de/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Direct funding for freelance visual artists in Germany; monitor current calls.",
    },
    {
        "source_id": "akademie_schloss_solitude",
        "name": "Akademie Schloss Solitude Fellowship",
        "url": "https://www.akademie-solitude.de/en/fellowship/solitude-fellowship/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "International fellowship/residency; cycle-based.",
    },
    {
        "source_id": "mondriaan_artist_start",
        "name": "Mondriaan Fund - Artist Start",
        "url": "https://www.mondriaanfonds.nl/en/apply-for-a-grant/grants/artist-start/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Early-career visual artists; Netherlands / Caribbean part of Kingdom eligibility.",
    },
    {
        "source_id": "mondriaan_artist_project",
        "name": "Mondriaan Fund - Artist Project",
        "url": "https://www.mondriaanfonds.nl/en/apply-for-a-grant/grants/artist-project/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Research/project/working period for artists.",
    },
    {
        "source_id": "swedish_arts_grants_visual",
        "name": "Swedish Arts Grants Committee - Visual and Applied Arts",
        "url": "https://www.konstnarsnamnden.se/en/stipendier-och-bidrag/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "listing",
        "trust_level": 4,
        "notes": "Work grants, project grants, residencies and international exchange/travel grants.",
    },
    {
        "source_id": "danish_arts_visual_international",
        "name": "Danish Arts Foundation - International Visual Arts Funding",
        "url": "https://www.kunst.dk/english/visual-arts-1/danish-arts-foundations-international-visual-arts-funding-programmes",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "International visual arts programmes; Danish and sometimes international eligibility.",
    },
    {
        "source_id": "taike_individual_grants",
        "name": "Taike / Finnish Arts and Culture Agency - Grants for Individuals",
        "url": "https://www.taike.fi/en/taike-supports/grants-individuals",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Working grants and project grants for professional artists.",
    },
    {
        "source_id": "frame_finland_grants",
        "name": "Frame Contemporary Art Finland - Grants",
        "url": "https://frame-finland.fi/en/grants/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Mobility, production and publication grants for international Finnish contemporary art projects.",
    },
    {
        "source_id": "nordic_culture_point_mobility",
        "name": "Nordic Culture Point - Mobility Funding",
        "url": "https://www.nkk.org/en/mobility-funding/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Professional artists/cultural practitioners in Nordic and Baltic region.",
    },
    {
        "source_id": "nordic_culture_fund_nemo",
        "name": "Nordic Culture Fund - NEMO",
        "url": "https://nordiskkulturfond.org/en/funding-programmes/nemo-northern-european-mobility-opportunity",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Early-stage individual artists and arts practitioners.",
    },
    {
        "source_id": "cnap_artist_project",
        "status": "inactive",
        "name": "CNAP - Soutien à un projet artistique",
        "url": "https://www.cnap.fr/soutien-creation/projets-artistes/modalites-de-candidature",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "French visual arts project support; eligibility must be parsed carefully.",
    },
    {
        "source_id": "institut_francais_cite_residency",
        "name": "Institut français x Cité internationale des arts Residency",
        "url": "https://www.institutfrancais.com/en/programme/residence-and-professional-mobility/residencies-institut-francais-x-cite-internationale",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "International residency in Paris; visual arts/photography included.",
    },
    {
        "source_id": "european_cultural_foundation_open_calls",
        "name": "European Cultural Foundation - Open Calls",
        "url": "https://culturalfoundation.eu/communities/open-calls/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "weekly",
        "parser_type": "listing",
        "trust_level": 4,
        "notes": "Transnational cultural collaboration; not always visual-art-specific.",
    },
    {
        "source_id": "roberto_cimetta_fund",
        "name": "Roberto Cimetta Fund - Mobility Grants",
        "url": "https://www.cimettafund.org/en/mobility-grants/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Euro-Med, Arab world and Middle East mobility grants.",
    },
    {
        "source_id": "visegrad_visual_sound_residency",
        "name": "International Visegrad Fund - Visual and Sound Artist Residency",
        "url": "https://www.visegradfund.org/visual-and-sound-artist-residency-apply",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "V4 visual/sound artists; opens seasonally.",
    },
    {
        "source_id": "emap_emare_residencies",
        "name": "European Media Art Platform - EMAP Residencies",
        "url": "https://call.emare.eu/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "dynamic_js",
        "trust_level": 4,
        "notes": "Digital/media/robotic/bio art residencies; EU Creative Europe supported.",
    },
    {
        "source_id": "arts_council_ireland_visual_bursary",
        "name": "Arts Council Ireland - Visual Arts Bursary",
        "url": "https://artscouncil.ie/funding-opportunities/bursary-award-round-1/visual-arts-bursary-award-round-1/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Individual visual artists; cycle-based.",
    },

    # ── Азия и Тихий океан ───────────────────────────────────────────────────
    {
        "source_id": "culture360_asef",
        "name": "Culture360 / ASEF - Opportunities",
        "url": "https://culture360.asef.org/opportunities/",
        "source_type": "aggregator",
        "region": "asia",
        "crawl_frequency": "weekly",
        "parser_type": "listing",
        "trust_level": 4,
        "notes": "Asia-Europe Foundation; grants, residencies, events for artists.",
    },
    {
        "source_id": "asian_cultural_council",
        "name": "Asian Cultural Council - Grant Opportunities",
        "url": "https://www.asianculturalcouncil.org/grant-opportunities",
        "source_type": "foundation",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Major grants for Asian and American artists; visual arts focus.",
    },
    {
        "source_id": "nac_singapore_creation",
        "name": "National Arts Council Singapore - Creation Grant",
        "url": "https://www.nac.gov.sg/support/funding-and-schemes/creation-grant/overview",
        "source_type": "government",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Singapore-based artists; creation and presentation grants.",
    },
    {
        "source_id": "hkadc_project_grant",
        "name": "Hong Kong Arts Development Council - Project Grant",
        "url": "https://www.hkadc.org.hk/en/grants-and-scholarship/grants/project-grant",
        "source_type": "government",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "HK-based visual artists; project funding.",
    },
    {
        "source_id": "ncafroc_taiwan",
        "name": "National Culture and Arts Foundation Taiwan - Grants",
        "url": "https://www.ncafroc.org.tw/grants_award.html",
        "source_type": "government",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Taiwan artists; annual grants program.",
    },
    {
        "source_id": "jpf_exhibit_support",
        "name": "Japan Foundation - Exhibition Support",
        "url": "https://www.jpf.go.jp/e/project/culture/exhibit/supportlist/",
        "source_type": "government",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Japanese artists and Japanese art exhibitions internationally.",
    },
    {
        "source_id": "arko_international_grants",
        "name": "Arts Council Korea - International Grants",
        "url": "https://www.arko.or.kr/eng/international/grants",
        "source_type": "government",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Korean artists; international exchange and residency grants.",
    },
    {
        "source_id": "gokams_korea",
        "name": "GOKAMS - Korea Arts Management Service",
        "url": "https://www.gokams.or.kr/eng/program/program02.aspx",
        "source_type": "government",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Korea Arts Management Service; international exchange programs.",
    },
    {
        "source_id": "ficart_awards",
        "name": "FICART - Awards and Grants",
        "url": "https://ficart.org/awards-and-grants",
        "source_type": "foundation",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 3,
        "notes": "Filipino contemporary art foundation.",
    },
    {
        "source_id": "inlaks_fine_art_award",
        "name": "Inlaks Foundation - Fine Art Award",
        "url": "https://inlaksfoundation.org/opportunities/awards/inlaks-fine-art-award/",
        "source_type": "foundation",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "India-based visual artists; significant career award.",
    },
    {
        "source_id": "mmf_india",
        "name": "Mrinalini Mukherjee Foundation - Creative Arts Grant",
        "url": "https://mrinalinimukherjeefoundation.com/exhibitions/32-call-for-proposals-mrinalini-mukherjee-creative-arts-deadline-20-may-2026/",
        "source_type": "foundation",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 3,
        "notes": "India; visual art / craft; URL per-cycle, may need updating.",
    },
    {
        "source_id": "khoj_residency",
        "name": "Khoj Studios - International Residency",
        "url": "https://khojstudios.org/opportunities/",
        "source_type": "foundation",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "India; experimental/contemporary art residencies and open calls.",
    },
    {
        "source_id": "mycreative_malaysia",
        "name": "MyCreative Ventures - Grants (Malaysia)",
        "url": "https://www.mycreative.com.my/grants",
        "source_type": "government",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 3,
        "notes": "Malaysia-based creative practitioners.",
    },
    {
        "source_id": "mekong_cultural_hub",
        "name": "Mekong Cultural Hub - Programs",
        "url": "https://www.mekongculturalhub.org/programs-1/",
        "source_type": "foundation",
        "region": "asia",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 3,
        "notes": "Southeast Asia; arts and culture grants/residencies.",
    },

    # ── MENA (Ближний Восток и Северная Африка) ───────────────────────────────
    {
        "source_id": "mawred_production_awards",
        "name": "Mawred - Production Awards",
        "url": "https://mawred.org/artistic-creativity/production-awards/?lang=en",
        "source_type": "foundation",
        "region": "mena",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Arab artists; production and creation grants.",
    },
    {
        "source_id": "mophradat_grants",
        "name": "Mophradat - Grants for Artists",
        "url": "https://mophradat.org/en/index/grants-for-artists/",
        "source_type": "foundation",
        "region": "mena",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Arab visual artists; production, research, residency grants.",
    },
    {
        "source_id": "alserkal_grants",
        "name": "Alserkal Foundation - Grants",
        "url": "https://alserkal.online/foundation/grants/",
        "source_type": "foundation",
        "region": "mena",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Dubai-based; visual and contemporary arts.",
    },
    {
        "source_id": "sharjah_art_open_calls",
        "status": "inactive",
        "name": "Sharjah Art Foundation - Open Calls",
        "url": "https://sharjahart.org/en/open-calls/list",
        "source_type": "foundation",
        "region": "mena",
        "crawl_frequency": "weekly",
        "parser_type": "listing",
        "trust_level": 4,
        "notes": "Sharjah; international open calls for visual artists.",
    },

    # ── Латинская Америка и Испания ───────────────────────────────────────────
    {
        "source_id": "fundacion_amaamoedo",
        "name": "Fundación AMA Amoedo",
        "url": "https://www.fundacionamaamoedo.org/",
        "source_type": "foundation",
        "region": "latam",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 3,
        "notes": "Galicia/Spain; visual art support.",
    },
    {
        "source_id": "fundacion_botin_arts",
        "name": "Fundación Botín - Plastic Arts Grants",
        "url": "https://fundacionbotin.org/en/grants-and-calls-for-applications/plastic-arts-grants/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Spain; significant grant for visual artists.",
    },
    {
        "source_id": "nalac_grants",
        "name": "NALAC - Grants (Latinx Arts)",
        "url": "https://www.nalac.org/grants/",
        "source_type": "foundation",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Latinx artists in USA; visual arts included.",
    },
    {
        "source_id": "cintas_fellowships",
        "name": "Cintas Foundation - Fellowships",
        "url": "https://cintasfoundation.org/fellowships",
        "source_type": "foundation",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Cuban-heritage visual artists.",
    },

    # ── Канада ────────────────────────────────────────────────────────────────
    {
        "source_id": "canada_council_grants",
        "name": "Canada Council for the Arts - Grants",
        "url": "https://canadacouncil.ca/funding/grants",
        "source_type": "government",
        "region": "north_america",
        "crawl_frequency": "weekly",
        "parser_type": "listing",
        "trust_level": 5,
        "notes": "Major national grants; visual arts component.",
    },
    {
        "source_id": "oac_visual_creation",
        "name": "Ontario Arts Council - Visual Artists Creation Projects",
        "url": "https://www.arts.on.ca/grants/visual-artists-creation-projects",
        "source_type": "government",
        "region": "north_america",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Ontario-based visual artists.",
    },
    {
        "source_id": "calq_artists_grants",
        "name": "CALQ - Grants for Artists (Quebec)",
        "url": "https://www.calq.gouv.qc.ca/en/grants/grants-programs/artists",
        "source_type": "government",
        "region": "north_america",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Quebec-based artists; creation and research grants.",
    },
    {
        "source_id": "bc_arts_visual",
        "name": "BC Arts Council - Visual and Crafts Artists",
        "url": "https://www.bcartscouncil.ca/program/visual-artists-crafts-artists-critics-curators/",
        "source_type": "government",
        "region": "north_america",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "British Columbia visual artists; project and travel grants.",
    },
    {
        "source_id": "toronto_arts_visual",
        "name": "Toronto Arts Council - Visual Artists Program",
        "url": "https://torontoartscouncil.org/grants/visual-artists-program-creation/",
        "source_type": "government",
        "region": "north_america",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Toronto-based visual artists; creation grants.",
    },

    # ── США (дополнительно) ───────────────────────────────────────────────────
    {
        "source_id": "nysca_artists",
        "name": "New York State Council on the Arts - Support for Artists",
        "url": "https://arts.ny.gov/funding-areas/support-artists",
        "source_type": "government",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "NY-based artists; individual artist grants.",
    },

    # ── EU / Агрегаторы ───────────────────────────────────────────────────────
    {
        "source_id": "british_council_connections",
        "name": "British Council - Connections Through Culture",
        "url": "https://arts.britishcouncil.org/connections-through-culture",
        "source_type": "foundation",
        "region": "international",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "International mobility and collaboration; visual arts included.",
    },
    {
        "source_id": "creatives_unite",
        "name": "Creatives Unite - Funding & Residencies",
        "url": "https://creativesunite.eu/",
        "source_type": "aggregator",
        "region": "europe",
        "crawl_frequency": "weekly",
        "parser_type": "listing",
        "trust_level": 3,
        "notes": "EU Creative Europe aggregator; open calls, grants, residencies.",
    },
    {
        "source_id": "artenda_net",
        "name": "Artenda.net",
        "url": "https://artenda.net/",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "listing",
        "trust_level": 3,
        "notes": "International grants and open calls aggregator for visual artists.",
    },
    {
        "source_id": "opencall_ca",
        "name": "OpenCall.ca",
        "url": "https://opencall.ca/",
        "source_type": "aggregator",
        "region": "north_america",
        "crawl_frequency": "weekly",
        "parser_type": "listing",
        "trust_level": 3,
        "notes": "Canada-focused open calls, grants, residencies aggregator.",
    },
]


def seed():
    init_db()
    conn = get_conn()
    upserted = 0
    with conn:
        for s in SOURCES:
            try:
                conn.execute("""
                    INSERT INTO sources
                    (source_id, name, url, source_type, region, discipline_focus,
                     crawl_frequency, parser_type, trust_level, requires_manual_review, notes)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT(source_id) DO UPDATE SET
                        name = excluded.name,
                        url = excluded.url,
                        source_type = excluded.source_type,
                        region = excluded.region,
                        discipline_focus = excluded.discipline_focus,
                        crawl_frequency = excluded.crawl_frequency,
                        parser_type = excluded.parser_type,
                        trust_level = excluded.trust_level,
                        requires_manual_review = excluded.requires_manual_review,
                        notes = excluded.notes
                """, (
                    s["source_id"], s["name"], s["url"], s["source_type"],
                    s.get("region", "international"), s.get("discipline_focus", "visual art"),
                    s.get("crawl_frequency", "weekly"), s["parser_type"],
                    s.get("trust_level", 3), s.get("requires_manual_review", 0),
                    s.get("notes", ""),
                ))
                upserted += 1
            except Exception as e:
                print(f"Error upserting {s['source_id']}: {e}")

    print(f"Seeded: {upserted} sources upserted.")
    conn.close()


if __name__ == "__main__":
    seed()
