"""
Source Registry — начальный список источников.
Запусти: python -m src.database.seed_sources
"""

from src.database.db import get_conn, init_db

SOURCES = [
    # ── Агрегаторы высокой плотности ──────────────────────────────────────────
    {
        "source_id": "nyfa_opportunities",
        "name": "NYFA Opportunities — Visual Arts Grants",
        "url": "https://www.nyfa.org/opportunities/?discipline=Visual+Arts&type=Grant",
        "source_type": "aggregator",
        "region": "usa",
        "crawl_frequency": "weekly",
        "parser_type": "dynamic_js",
        "trust_level": 5,
        "notes": "Подтверждено: JS-рендеринг, Playwright. 48K символов контента.",
    },
    {
        "source_id": "artconnect",
        "parser_type": "listing",
        "name": "ArtConnect Grants & Stipends",
        "url": "https://www.artconnect.com/opportunities/grant-or-stipend",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "daily",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Международные гранты, стипендии, open calls. Актуальный URL с фильтром.",
    },
    {
        "source_id": "on_the_move",
        "name": "On the Move — Funding Guides",
        "url": "https://on-the-move.org/resources/funding",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "2000+ grants, scholarships, residencies. Mobility и international funding.",
    },
    {
        "source_id": "culture_moves_europe",
        "name": "Culture Moves Europe",
        "url": "https://culture.ec.europa.eu/culture-moves-europe",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Европейская mobility-схема для artists, включая visual arts.",
    },
    {
        "source_id": "transartists",
        "name": "TransArtists / DutchCulture Funding",
        "url": "https://www.transartists.org/en/opportunities",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Резиденции и funding for residencies, международная мобильность.",
    },
    {
        "source_id": "res_artis",
        "name": "Res Artis — Open Calls & Funding",
        "url": "https://www.resartis.org/en/opportunities/",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Residency-related funding и open calls от мировых резиденций.",
    },
    {
        "source_id": "artdeadline",
        "name": "ArtDeadline.com — Grants",
        "url": "https://artdeadline.com/?type=Grant",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "daily",
        "parser_type": "listing",
        "trust_level": 4,
        "notes": "Листинг-агрегатор. Парсим каждую страницу /ops/ отдельно через listing_fetcher.",
    },
    {
        "source_id": "submittable_discover",
        "name": "Submittable Discover — Grants",
        "url": "https://www.submittable.com/discover/?category=grants&q=visual+art",
        "source_type": "submission_platform",
        "region": "international",
        "crawl_frequency": "daily",
        "parser_type": "dynamic_js",
        "trust_level": 4,
        "notes": "Marketplace. JS-рендеринг через Playwright.",
    },
    {
        "source_id": "beam_arts",
        "name": "Beam Arts — Artist Funding Directory",
        "url": "https://www.beamarts.gr/artist-funding-directory",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Каталог grants/funding worldwide для artists. Обновлён февраль 2026.",
    },
    {
        "source_id": "fractured_atlas", "status": "inactive",
        "name": "Fractured Atlas — Artist Opportunity Database",
        "url": "https://fracturedatlas.notion.site/Artist-Opportunity-Database",
        "source_type": "aggregator",
        "region": "international",
        "crawl_frequency": "weekly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Notion-база: grants, funders, awards, fellowships, open calls, residencies worldwide.",
    },

    # ── Прямые фонды — визуальное искусство ────────────────────────────────────
    {
        "source_id": "fca_emergency",
        "name": "Foundation for Contemporary Arts — Emergency Grants",
        "url": "https://www.foundationforcontemporaryarts.org/grants/emergency-grants/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Срочные гранты $500-$3,000 для visual и performing artists в США. Открыты круглый год.",
    },
    {
        "source_id": "creative_capital",
        "name": "Creative Capital Foundation",
        "url": "https://creative-capital.org/awards/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "dynamic_js",
        "trust_level": 5,
        "notes": "JS-рендеринг, Playwright. Страница awards с актуальными грантами.",
    },
    {
        "source_id": "sustainable_arts",
        "name": "Sustainable Arts Foundation",
        "url": "https://www.sustainableartsfoundation.org/awards",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "$5,000 x 20 художников. Для artists с детьми.",
    },
    {
        "source_id": "artadia",
        "name": "Artadia Awards",
        "url": "https://artadia.org/awards/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "HTML + JSON-LD. Дедлайны по городам (LA, Chicago, NYC, SF).",
    },
    {
        "source_id": "macdowell",
        "name": "MacDowell Fellowships",
        "url": "https://macdowell.org/fellowships/",
        "source_type": "residency",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Residency fellowships, включая visual arts.",
    },
    {
        "source_id": "joan_mitchell",
        "name": "Joan Mitchell Foundation — Grants",
        "url": "https://www.joanmitchellfoundation.org/artist-programs/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Grants для visual artists.",
    },
    {
        "source_id": "pollock_krasner",
        "name": "Pollock-Krasner Foundation",
        "url": "https://pkf.org/our-grants/",
        "source_type": "fund",
        "region": "international",
        "crawl_frequency": "monthly",
        "parser_type": "dynamic_js",
        "trust_level": 5,
        "notes": "Playwright нужен.",
    },
    {
        "source_id": "usa_artists",
        "name": "United States Artists",
        "url": "https://www.unitedstatesartists.org/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "USA Fellows program.",
    },
    {
        "source_id": "anonymous_was_a_woman",
        "name": "Anonymous Was A Woman",
        "url": "https://anonymouswasawoman.org/",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "$25,000 grants to women visual artists 45+.",
    },
    {
        "source_id": "andy_warhol_fnd",
        "name": "Andy Warhol Foundation for the Visual Arts",
        "url": "https://warholfoundation.org/grants/",
        "source_type": "fund",
        "region": "international",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 5,
        "notes": "Гранты организациям, поддерживающим contemporary visual art.",
    },
    {
        "source_id": "jerome_fnd",
        "name": "Jerome Foundation",
        "url": "https://jeromefdn.org/grants",
        "source_type": "fund",
        "region": "usa",
        "crawl_frequency": "monthly",
        "parser_type": "dynamic_js",
        "trust_level": 4,
        "notes": "Playwright нужен.",
    },

    # ── Европейские и международные фонды ─────────────────────────────────────
    {
        "source_id": "british_council_arts", "status": "inactive",
        "name": "British Council — Arts Funding",
        "url": "https://www.britishcouncil.org/arts/funding",
        "source_type": "government",
        "region": "uk",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Mobility и international arts grants от British Council.",
    },
    {
        "source_id": "goethe_fnd",
        "name": "Goethe-Institut — Grants & Residencies",
        "url": "https://www.goethe.de/en/kul/the/prg.html",
        "source_type": "government",
        "region": "international",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Стипендии, резиденции, проектные гранты.",
    },
    {
        "source_id": "pro_helvetia",
        "name": "Pro Helvetia — Swiss Arts Council",
        "url": "https://prohelvetia.ch/en/grants/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Grants for international projects.",
    },

    # ── Новые источники — Европа ──────────────────────────────────────────────
    {
        "source_id": "stiftung_kunstfonds",
        "name": "Stiftung Kunstfonds",
        "url": "https://www.kunstfonds.de/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Direct funding for freelance visual artists in Germany; monitor current calls.",
    },
    {
        "source_id": "akademie_schloss_solitude",
        "name": "Akademie Schloss Solitude Fellowship",
        "url": "https://www.akademie-solitude.de/en/fellowship/solitude-fellowship/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "International fellowship/residency; cycle-based.",
    },
    {
        "source_id": "mondriaan_artist_start",
        "name": "Mondriaan Fund - Artist Start",
        "url": "https://www.mondriaanfonds.nl/en/apply-for-a-grant/grants/artist-start/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Early-career visual artists; Netherlands / Caribbean part of Kingdom eligibility.",
    },
    {
        "source_id": "mondriaan_artist_project",
        "name": "Mondriaan Fund - Artist Project",
        "url": "https://www.mondriaanfonds.nl/en/apply-for-a-grant/grants/artist-project/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Research/project/working period for artists.",
    },
    {
        "source_id": "swedish_arts_grants_visual",
        "name": "Swedish Arts Grants Committee - Visual and Applied Arts",
        "url": "https://www.konstnarsnamnden.se/en/stipendier-och-bidrag/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "listing",
        "trust_level": 4,
        "notes": "Work grants, project grants, residencies and international exchange/travel grants.",
    },
    {
        "source_id": "danish_arts_visual_international",
        "name": "Danish Arts Foundation - International Visual Arts Funding",
        "url": "https://www.kunst.dk/english/visual-arts-1/danish-arts-foundations-international-visual-arts-funding-programmes",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "International visual arts programmes; Danish and sometimes international eligibility.",
    },
    {
        "source_id": "taike_individual_grants",
        "name": "Taike / Finnish Arts and Culture Agency - Grants for Individuals",
        "url": "https://www.taike.fi/en/taike-supports/grants-individuals",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Working grants and project grants for professional artists.",
    },
    {
        "source_id": "frame_finland_grants",
        "name": "Frame Contemporary Art Finland - Grants",
        "url": "https://frame-finland.fi/en/grants/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Mobility, production and publication grants for international Finnish contemporary art projects.",
    },
    {
        "source_id": "nordic_culture_point_mobility",
        "name": "Nordic Culture Point - Mobility Funding",
        "url": "https://www.nkk.org/en/mobility-funding/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Professional artists/cultural practitioners in Nordic and Baltic region.",
    },
    {
        "source_id": "nordic_culture_fund_nemo",
        "name": "Nordic Culture Fund - NEMO",
        "url": "https://nordiskkulturfond.org/en/funding-programmes/nemo-northern-european-mobility-opportunity",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Early-stage individual artists and arts practitioners.",
    },
    {
        "source_id": "cnap_artist_project",
        "name": "CNAP - Soutien à un projet artistique",
        "url": "https://www.cnap.fr/soutien-creation/projets-artistes/modalites-de-candidature",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "French visual arts project support; eligibility must be parsed carefully.",
    },
    {
        "source_id": "institut_francais_cite_residency",
        "name": "Institut français x Cité internationale des arts Residency",
        "url": "https://www.institutfrancais.com/en/programme/residence-and-professional-mobility/residencies-institut-francais-x-cite-internationale",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "International residency in Paris; visual arts/photography included.",
    },
    {
        "source_id": "european_cultural_foundation_open_calls",
        "name": "European Cultural Foundation - Open Calls",
        "url": "https://culturalfoundation.eu/communities/open-calls/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "weekly",
        "parser_type": "listing",
        "trust_level": 4,
        "notes": "Transnational cultural collaboration; not always visual-art-specific.",
    },
    {
        "source_id": "roberto_cimetta_fund",
        "name": "Roberto Cimetta Fund - Mobility Grants",
        "url": "https://www.cimettafund.org/en/mobility-grants/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Euro-Med, Arab world and Middle East mobility grants.",
    },
    {
        "source_id": "visegrad_visual_sound_residency",
        "name": "International Visegrad Fund - Visual and Sound Artist Residency",
        "url": "https://www.visegradfund.org/visual-and-sound-artist-residency-apply",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "V4 visual/sound artists; opens seasonally.",
    },
    {
        "source_id": "emap_emare_residencies",
        "name": "European Media Art Platform - EMAP Residencies",
        "url": "https://call.emare.eu/",
        "source_type": "foundation",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "dynamic_js",
        "trust_level": 4,
        "notes": "Digital/media/robotic/bio art residencies; EU Creative Europe supported.",
    },
    {
        "source_id": "arts_council_ireland_visual_bursary",
        "name": "Arts Council Ireland - Visual Arts Bursary",
        "url": "https://artscouncil.ie/funding-opportunities/bursary-award-round-1/visual-arts-bursary-award-round-1/",
        "source_type": "government",
        "region": "europe",
        "crawl_frequency": "monthly",
        "parser_type": "html",
        "trust_level": 4,
        "notes": "Individual visual artists; cycle-based.",
    },
]


def seed():
    init_db()
    conn = get_conn()
    upserted = 0
    with conn:
        for s in SOURCES:
            try:
                conn.execute("""
                    INSERT INTO sources
                    (source_id, name, url, source_type, region, discipline_focus,
                     crawl_frequency, parser_type, trust_level, requires_manual_review, notes)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT(source_id) DO UPDATE SET
                        name = excluded.name,
                        url = excluded.url,
                        source_type = excluded.source_type,
                        region = excluded.region,
                        discipline_focus = excluded.discipline_focus,
                        crawl_frequency = excluded.crawl_frequency,
                        parser_type = excluded.parser_type,
                        trust_level = excluded.trust_level,
                        requires_manual_review = excluded.requires_manual_review,
                        notes = excluded.notes
                """, (
                    s["source_id"], s["name"], s["url"], s["source_type"],
                    s.get("region", "international"), s.get("discipline_focus", "visual art"),
                    s.get("crawl_frequency", "weekly"), s["parser_type"],
                    s.get("trust_level", 3), s.get("requires_manual_review", 0),
                    s.get("notes", ""),
                ))
                upserted += 1
            except Exception as e:
                print(f"Error upserting {s['source_id']}: {e}")

    print(f"Seeded: {upserted} sources upserted.")
    conn.close()


if __name__ == "__main__":
    seed()
